server.port: 8080

logging:
  level:
    root: WARN

spring:
  output:
    ansi:
      enabled: always
  security:
    debug: true
  logging:
    level:
      org:
        springframework:
          security: DEBUG

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysqlcontainerforapp:3306/api_clinica?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: root
    password: letmein
  jpa:
    show-sql: true
    #hibernate: # Optei por usar o FlyWay para versionamento do banco
      #ddl-auto: none
      #ddl-auto: update # Atualiza o schema do banco automaticamente para que fique igual as entidades, inclusive apaga o que for necessário
      #ddl-auto: create # Cria o schema do banco automaticamente, se ja existir sera excluido e recriado
      #ddl-auto: create-drop # Semelhante ao create mas o schema é removido toda vez que encerrar a aplicação
      #ddl-auto: validate # Apenas valida o schema do banco e lancará exceções se não estiver de acordo com as entidades mas não altera nada
    properties:
      hibernate.format_sql: true
  data:
    web:
      pageable:
        page-parameter: pagina
        size-parameter: tamanho
      sort:
        sort-parameter: ordem

api:
  security:
    token:
      secret: ${JWT_SECRET:12345678}