server.port: 8080

logging:
  level:
    root: INFO

spring:
  output:
    ansi:
      enabled: always
  security:
    debug: true
  logging:
    level:
      org:
        springframework:
          security: DEBUG

  datasource:
   url: jdbc:h2:mem:testdb
   username: sa
   password:

  flyway:
   enabled: false

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update # validate | update | create | create-drop
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

  data:
    web:
      pageable:
        page-parameter: pagina
        size-parameter: tamanho
      sort:
        sort-parameter: ordem

api:
  security:
    token:
      secret: ${JWT_SECRET:SpringTokenizerRocks}

module-name: API Clinica Medica em Container Docker
api-version: 0.9.8
api-description: API Clinica Medica
api-contact-name: Edson Freitas
api-contact-url: http://github.com/edsonsfreitas
api-contact-email: edson.s.freitas@gmail.com

spring-doc:
  api-docs:
    resolve-schema-properties: true
    swagger-ui:
      csrf:
        enabled=true