server.port: 8080

logging:
  level:
    root: INFO

spring:
  output:
    ansi:
      enabled: always
  security:
    debug: true
  logging:
    level:
      org:
        springframework:
          security: DEBUG

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysqlcontainerforapp:3306/api_clinica?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: admin
    password: letmein
  jpa:
    show-sql: true
    #hibernate: # Optei por usar o FlyWay para versionamento do banco
    properties:
      hibernate.format_sql: true
  data:
    web:
      pageable:
        page-parameter: pagina
        size-parameter: tamanho
      sort:
        sort-parameter: ordem

api:
  security:
    token:
      secret: ${JWT_SECRET:SpringTokenizerRocks}


module-name: API Clinica Medica em Container Docker
api-version: 0.9.8
api-description: API Clinica Medica
api-contact-name: Edson Freitas
api-contact-url: http://github.com/edsonsfreitas
api-contact-email: edson.s.freitas@gmail.com

spring-doc:
  api-docs:
    resolve-schema-properties: true
    swagger-ui:
      csrf:
        enabled=true